import 'package:tiktok_mobile/core/network/api_client.dart';
import 'package:tiktok_mobile/core/network/api_response.dart';
import 'package:tiktok_mobile/features/interaction/data/interaction_model.dart';

/// interaction-service (`/api/v1/interactions`). Every write needs a token;
/// `like-status` works without one but then always answers `liked: false`.
///
/// No endpoint here checks that the video exists — interaction-service holds
/// no video data and never asks video-service — so there is no
/// `VIDEO_NOT_FOUND` to handle (interaction doc 3).
class InteractionRemoteDatasource {
  InteractionRemoteDatasource(this._apiClient);

  final ApiClient _apiClient;

  /// Idempotent: liking twice answers `liked: true` with the count unchanged,
  /// so a retry after a dropped connection cannot double-count.
  Future<LikeStatus> like(String videoId) async {
    final response = await _apiClient.post<Map<String, dynamic>>(
      '/interactions/videos/$videoId/like',
    );
    return _unwrap(response.data!);
  }

  /// Idempotent the same way: unliking what was never liked is a plain 200.
  Future<LikeStatus> unlike(String videoId) async {
    final response = await _apiClient.delete<Map<String, dynamic>>(
      '/interactions/videos/$videoId/like',
    );
    return _unwrap(response.data!);
  }

  Future<LikeStatus> getLikeStatus(String videoId) async {
    final response = await _apiClient.get<Map<String, dynamic>>(
      '/interactions/videos/$videoId/like-status',
    );
    return _unwrap(response.data!);
  }

  /// The one call that moves `viewCount`. Fire it once when playback starts,
  /// never on a timer (doc 3.8).
  ///
  /// [playId] identifies one playback and is generated by the client when
  /// playback starts: the server counts one view per playId, so a retry must
  /// resend the same one (it answers `counted: false`) and a replay must send
  /// a new one.
  Future<void> recordView(String videoId, {required String playId}) {
    return _apiClient.post<void>(
      '/interactions/videos/$videoId/view',
      data: {'playId': playId},
    );
  }

  /// One call per finished watch session — not per progress tick.
  ///
  /// [watchedMs] is time actually played, looped replays added together;
  /// seeking and pausing do not move it. [durationMs] comes from the player
  /// rather than `VideoResponse.durationSeconds`, because what the server
  /// wants is the ratio of what could actually be played (doc 3.9).
  Future<void> recordWatch(
    String videoId, {
    required int watchedMs,
    required int durationMs,
  }) {
    return _apiClient.post<void>(
      '/interactions/videos/$videoId/watch',
      data: {'watchedMs': watchedMs, 'durationMs': durationMs},
    );
  }

  /// Every call counts as another share — no per-user dedup. Call it after the
  /// share actually happened, and never retry it (doc 3.7).
  Future<void> share(String videoId) {
    return _apiClient.post<void>('/interactions/videos/$videoId/share');
  }

  /// Public, and the authoritative source for the four counters — the copies
  /// on `VideoResponse` arrive over Kafka and lag behind (doc 3.10).
  Future<InteractionCounts> getCounts(String videoId) async {
    final response = await _apiClient.get<Map<String, dynamic>>(
      '/interactions/videos/$videoId/counts',
    );
    return ApiResponse<InteractionCounts>.fromJson(
      response.data!,
      (json) => InteractionCounts.fromJson(json as Map<String, dynamic>),
    ).data!;
  }

  LikeStatus _unwrap(Map<String, dynamic> body) {
    return ApiResponse<LikeStatus>.fromJson(
      body,
      (json) => LikeStatus.fromJson(json as Map<String, dynamic>),
    ).data!;
  }
}
